name: Deploy Cloudflare Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Run lint
      - name: Lint
        run: npm run lint

      # Build app/dist
      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.API_URL }}

      # Deploy to Cloudflare Pages
      # Temporarily installs wrangler to deploy build to cloudflare
      - name: Deploy
        run: npx wrangler@4 pages deploy dist --project-name=portfolio --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
